print("Bienvenidos a python 🐍")
print("######cartel 6°B######")
print("######PROGRAMANDO######")
print("######ESTUDIANDO######")
print("######APRENDIENDO######")
print("#SE CREARAN PROYECTOS#")
print("👍😊🐾😎🎶👽🐨🐶🙃")
print("#          💡         ")
print(" ##LA FRASE DEL DIA ES##")
print("ENTONCES APLIQUESMOLO🐶")
print("BIENVENIDO CICLO 2025-2026")